### ISSUE TITLE
Инициализация приложения

### ISSUE THREAD

**Issue by orby-tech** [LIli-Gimadut/course-platform#1]
1) Выбрать инструменты для фронтенда
2) Инициализировать фронтенд React + Typescript
3) Выбрать инструменты для бекенда
4) Инициализировать бекенд с Nest.js + Typescript https://docs.nestjs.com/first-steps

**Comment by LIli-Gimadut** [comment]
Кажется, я это сделала..
По крайней мере, создала 2 проекта через команды в командной строке, открыла их через VSCodium и обнаружила там файлы, которые там должны быть, судя по скриншотам из интернета :octocat:

**Comment by orby-tech** [comment]
Молодец)

1) Нужно проверить что они просто запускаются
2) Добавить все что не должно быть в репозитории в gitignore
3) Создать ветку(в гит) под инициализацию приложения
4) Сделать коммит
5) Сделать пулреквест
